apiVersion: v1
kind: ConfigMap
metadata:
  name: inventory-config
  namespace: inventory-system
data:
  DB_HOST: {{ .Values.db.host }}
  DB_PORT: {{ .Values.db.port | quote }}
  DB_NAME: {{ .Values.db.name }}
  APP_ENV: {{ .Values.app.env }}
