apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: inventory-network-policy
  namespace: inventory-system
spec:
  podSelector:
    matchLabels:
      app: inventory-db
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: inventory-backend
    ports:
    - protocol: TCP
      port: 5432
